#this is a comment
image: alpine:latest

variables:
    BASEURL: "https://timetothink.io"
    KEYCDN_USER: "tristangodfrey"
    KEYCDN_ZONE_NAME: "timetothink"

before_script:
    - apk update
    - apk add curl

push_keycdn:
    stage: deploy
    script:
    - apk add openssh rsync
    - mkdir -p ~/.ssh
    - echo 'rsync.keycdn.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBIsfz7Di7PsCUPnXy8GxHJGTbTXjLqdr2ZZeeM2U1Bf' >> ~/.ssh/known_hosts
    - echo "${SSH_DEPLOY_KEY}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - rsync -rtvz --chmod=D2755,F644 --delete src/ ${KEYCDN_USER}@rsync.keycdn.com:${KEYCDN_ZONE_NAME}/

    only:
    - master
